#!/bin/sh

set -e

# These commands were scraped out of Matlab from the output of "mexcuda -v", running from ninjaben/kilosort3-code.
# mexcuda is "foolish" enough to print out the full shell env and commands that it uses.
# So, we can run the same commands from the shell and avoid Matlab, licensing, etc. during the Docker build 

# In Matlab we can run:
#   cudaToolkitBin = '/usr/local/cuda/bin';
#   setenv('MW_NVCC_PATH', cudaToolkitBin);
#   mexcuda -v ...
# And part of the output will be these env var settings:
export PATH=":/usr/local/cuda/nvvm/bin:/usr/local/cuda/bin:;/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export INCLUDE=":/usr/lib/gcc/x86_64-linux-gnu/9/include;/usr/include/c++/9;/usr/include/c++/9/x86_64-linux-gnu;/usr/include/c++/9/backward;"

# In Matlab we can run commands like this:
#   mexGPUExampleSource = fullfile(matlabroot,'toolbox','parallel','gpu','extern','src','mex','mexGPUExample.cu')
#   mexcuda('-v', mexGPUExampleSource)
# And part of the output will be shell commands used to compile and link the binaries.
# We can run these verbatim, as long as we create the expected temp folders, first.
mkdir -p /tmp/mex_22156567986430_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/toolbox/parallel/gpu/extern/src/mex/mexGPUExample.cu" -o /tmp/mex_22156567986430_1/mexGPUExample.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22156567986430_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22156567986430_1/mexGPUExample.o /tmp/mex_22156567986430_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexGPUExample.mexa64
rm -f /tmp/mex_22156567986430_1/mexGPUExample.o
rm -f /tmp/mex_22156567986430_1/c_mexapi_version.o

# This and following commands were adapted from Kilosort's "mexGPUall.m", adding the "-v" flag for complete output.
# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/spikedetector3.cu')
mkdir -p /tmp/mex_22162833021212_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/spikedetector3.cu" -o /tmp/mex_22162833021212_1/spikedetector3.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22162833021212_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22162833021212_1/spikedetector3.o /tmp/mex_22162833021212_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o spikedetector3.mexa64
rm -f /tmp/mex_22162833021212_1/spikedetector3.o
rm -f /tmp/mex_22162833021212_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/spikedetector3PC.cu')
mkdir -p /tmp/mex_22175778817815_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/spikedetector3PC.cu" -o /tmp/mex_22175778817815_1/spikedetector3PC.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22175778817815_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22175778817815_1/spikedetector3PC.o /tmp/mex_22175778817815_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o spikedetector3PC.mexa64
rm -f /tmp/mex_22175778817815_1/spikedetector3PC.o
rm -f /tmp/mex_22175778817815_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexThSpkPC.cu')
mkdir -p /tmp/mex_22188564179418_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexThSpkPC.cu" -o /tmp/mex_22188564179418_1/mexThSpkPC.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22188564179418_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22188564179418_1/mexThSpkPC.o /tmp/mex_22188564179418_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexThSpkPC.mexa64
rm -f /tmp/mex_22188564179418_1/mexThSpkPC.o
rm -f /tmp/mex_22188564179418_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexGetSpikes2.cu')
mkdir -p /tmp/mex_22200592417409_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexGetSpikes2.cu" -o /tmp/mex_22200592417409_1/mexGetSpikes2.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22200592417409_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22200592417409_1/mexGetSpikes2.o /tmp/mex_22200592417409_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexGetSpikes2.mexa64
rm -f /tmp/mex_22200592417409_1/mexGetSpikes2.o
rm -f /tmp/mex_22200592417409_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '-dynamic', '-DENABLE_STABLEMODE', '/home/matlab/kilosort/CUDA/mexMPnu8.cu')
# add also -DENSURE_DETERM
mkdir -p /tmp/mex_22213425132140_1
/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/bin/nvcc -c -dc -DENABLE_STABLEMODE -DENSURE_DETERM -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /opt/matlab/R2022b/bin/glnxa64 -I"/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/include" --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexMPnu8.cu" -o /tmp/mex_22213425132140_1/mexMPnu8.o
/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/bin/nvcc -c -dc -DENABLE_STABLEMODE -DENSURE_DETERM -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /opt/matlab/R2022b/bin/glnxa64 -I"/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/include" --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22213425132140_1/c_mexapi_version.o
/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/bin/nvcc -dlink -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\" --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG /tmp/mex_22213425132140_1/mexMPnu8.o /tmp/mex_22213425132140_1/c_mexapi_version.o  -L"/opt/matlab/R2022b/bin/glnxa64" -lcudadevrt -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/opt/matlab/R2022b/sys/cuda/glnxa64/cuda/include" -o /tmp/mex_nU8RfXGej4_device.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_nU8RfXGej4_device.o /tmp/mex_22213425132140_1/mexMPnu8.o /tmp/mex_22213425132140_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /opt/matlab/R2022b/bin/glnxa64/libcudart.so.* /opt/matlab/R2022b/bin/glnxa64/libcudadevrt.a -o mexMPnu8.mexa64
rm -f /tmp/mex_22213425132140_1/mexMPnu8.o
rm -f /tmp/mex_22213425132140_1/c_mexapi_version.o
rm -f /tmp/mex_nU8RfXGej4_device.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexSVDsmall2.cu')
mkdir -p /tmp/mex_22234895832807_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexSVDsmall2.cu" -o /tmp/mex_22234895832807_1/mexSVDsmall2.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22234895832807_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22234895832807_1/mexSVDsmall2.o /tmp/mex_22234895832807_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexSVDsmall2.mexa64
rm -f /tmp/mex_22234895832807_1/mexSVDsmall2.o
rm -f /tmp/mex_22234895832807_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexWtW2.cu')
mkdir -p /tmp/mex_22249941180398_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexWtW2.cu" -o /tmp/mex_22249941180398_1/mexWtW2.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22249941180398_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22249941180398_1/mexWtW2.o /tmp/mex_22249941180398_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexWtW2.mexa64
rm -f /tmp/mex_22249941180398_1/mexWtW2.o
rm -f /tmp/mex_22249941180398_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexFilterPCs.cu')
mkdir -p /tmp/mex_22261240735422_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexFilterPCs.cu" -o /tmp/mex_22261240735422_1/mexFilterPCs.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22261240735422_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22261240735422_1/mexFilterPCs.o /tmp/mex_22261240735422_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexFilterPCs.mexa64
rm -f /tmp/mex_22261240735422_1/mexFilterPCs.o
rm -f /tmp/mex_22261240735422_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexClustering2.cu')
mkdir -p /tmp/mex_22272206665419_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexClustering2.cu" -o /tmp/mex_22272206665419_1/mexClustering2.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22272206665419_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22272206665419_1/mexClustering2.o /tmp/mex_22272206665419_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexClustering2.mexa64
rm -f /tmp/mex_22272206665419_1/mexClustering2.o
rm -f /tmp/mex_22272206665419_1/c_mexapi_version.o

# mexcuda('-v', '-largeArrayDims', '/home/matlab/kilosort/CUDA/mexDistances2.cu')
mkdir -p /tmp/mex_22285206894463_1
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/home/matlab/kilosort/CUDA/mexDistances2.cu" -o /tmp/mex_22285206894463_1/mexDistances2.o
/usr/local/cuda/bin/nvcc -c -DMX_COMPAT_64  -DMATLAB_DEFAULT_RELEASE=R2017b  -DUSE_MEX_CMD   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/opt/matlab/R2022b/extern/include" -I"/opt/matlab/R2022b/simulink/include" -I"/opt/matlab/R2022b/toolbox/parallel/gpu/extern/include/" -I"/usr/local/cuda/include" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=\"sm_80,compute_80\"  --dont-use-profile -ldir /usr/local/cuda/nvvm/libdevice --compiler-options=-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread,-fwrapv -std=c++11 -O2 -DNDEBUG "/opt/matlab/R2022b/extern/version/c_mexapi_version.c" -o /tmp/mex_22285206894463_1/c_mexapi_version.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/opt/matlab/R2022b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_22285206894463_1/mexDistances2.o /tmp/mex_22285206894463_1/c_mexapi_version.o   -Wl,--as-needed -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/usr/local/cuda/lib64 -L"/usr/local/cuda/lib64" -Wl,-rpath-link,/opt/matlab/R2022b/bin/glnxa64 -L"/opt/matlab/R2022b/bin/glnxa64" -Wl,-rpath-link,/opt/matlab/R2022b/extern/bin/glnxa64 -L"/opt/matlab/R2022b/extern/bin/glnxa64" -lMatlabDataArray -lmx -lmex -lmat -lm -lc -lstdc++ -lmwgpu /usr/local/cuda/lib64/libcudart.so.* -o mexDistances2.mexa64
rm -f /tmp/mex_22285206894463_1/mexDistances2.o
rm -f /tmp/mex_22285206894463_1/c_mexapi_version.o
