name: Docker Image CI

on:
 push:
    tags:
      - '*'

env:
  version-tag: "${{ github.ref_name }}"

jobs:

  matlab-parallel:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./matlab-parallel
        push: true
        tags: ninjaben/matlab-parallel:${{ env.version-tag }}
  kilosort3-code:
    needs: matlab-parallel
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        build-args: "VERSION=${{ env.version-tag }}"
        context: ./kilosort3-code
        push: true
        tags: ninjaben/kilosort3-code:${{ env.version-tag }}
  kilosort3:
    needs: kilosort3-code
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        build-args: "VERSION=${{ env.version-tag }}"
        context: ./kilosort3
        push: true
        tags: ninjaben/kilosort3:${{ env.version-tag }}
  phy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./phy
        push: true
        tags: ninjaben/phy:${{ env.version-tag }}
